### ISSUE TITLE
Séparer lineup et welcome

### ISSUE THREAD

**Issue by abelards** [parisrb/paris-rb.org#10]
Pourquoi pas une page de lineup qui correspond à ce qui est aujourd'hui sur la page lineup (et les sponsors en footer),
et une url /welcome qui fait les slides du welcome, comme le lineup d'aujourd'hui ?

**Comment by abelards** [comment]
- Le nouveau line-up n'aurait qu'une seule slide (donc une seule page)
- pourquoi pas le layout du site pour les liens, et un ajout dans le menu
- il n'aurait que le line-up, les sponsors, la date
- compatible mobile

**Comment by adrienpoly** [comment]
Completed in https://github.com/parisrb/paris-rb.org/pull/223
