### ISSUE TITLE
Refaire les pages + communiqué

### ISSUE THREAD

**Issue by abelards** [parisrb/paris-rb.org#138]
1. communiqué
2. CoC
3. gouvernance
4. notre mode de fonctionnement pour les talks
5. no show
6. embauche
FR+EN

**Comment by abelards** [comment]
@btrd une idée/reco pour poser facilement 12 pages statiques ?

**Comment by adrienpoly** [comment]
Je propose de mettre en place https://sitepress.cc/ c'est une GEM qui facilite la création de pages statiques et qui supporte nativement le markdown

Cela permettra par exemple d'avoir un fichier `views/pages/code-de-conduite.html.md` et l'url sur le site `/page/code-de-conduite`

On pourra aussi avoir une page index `/communiques` qui liste tous les communiqués.

@abelards peux tu nous communiquer le contenu des pages suivantes :

- [ ] gouvernance
- [ ] notre mode de fonctionnement pour les talks
- [ ] no show
- [ ] embauche FR+EN

**Comment by adrienpoly** [comment]
Completed in #223
