### ISSUE TITLE
Retreive new relic account

### ISSUE THREAD

**Issue by btrd** [parisrb/paris-rb.org#144]
On the website there is a newrelic script that's loaded, to which account is it linked ?

**Comment by adrienpoly** [comment]
dans https://github.com/parisrb/paris-rb.org/pull/179 la gem new_relic a été supprimée. Il n'y avait aucun fichier de config. 
Je ne vois pas trop l'intérêt d'un new relic pour ce site.

Par contre rajouter un Sentry (ou équivalant gratuit) oui
