### ISSUE TITLE
Links to Videos are broken

### ISSUE THREAD

**Issue by adrienpoly** [parisrb/paris-rb.org#162]
I have noticed several issues with videos : 

- I have a 500 when I visit https://paris-rb.org/videos/how-music-works-using-ruby-english

- When I visit this one https://paris-rb.org/videos/optimisation-tcp-le-clash, I have this error message
![Capture d’écran 2023-01-03 à 2 42 43 PM](https://user-images.githubusercontent.com/7847244/210368830-4afbc134-f22e-422e-ac61-94f3a8db39b3.jpg)

**Comment by btrd** [comment]
> I have a 500 when I visit https://paris-rb.org/videos/how-music-works-using-ruby-english

It happen when the description is missing
