### ISSUE TITLE
faire le meetup récurrent

### ISSUE THREAD

**Issue by abelards** [parisrb/paris-rb.org#171]

**Comment by adrienpoly** [comment]
@abelards peux tu nous donner un peu plus de contexte et détails sur tes attentes ?

Cela concerne un fonctionnalité du site ou juste un réglage de Meetup ?

**Comment by abelards** [comment]
Oui c'est la config du meetup lui-même.

**Comment by adrienpoly** [comment]
je considère que c'est done sinon hésite pas à réouvrir
