### ISSUE TITLE
Sponsors : position et affichage

### ISSUE THREAD

**Issue by tibastral** [parisrb/paris-rb.org#3]
Qu'on puisse les trier dans l'ordre qu'on veut.

Bisous

**Comment by abelards** [comment]
Et pourquoi pas une classe / une taille / des étoiles différentes en fonction de la durée de sponsoring ?

**Comment by abelards** [comment]
L'ordre sûrement dans le modèle
https://github.com/parisrb/rubyparis.org/blob/master/app/models/sponsor.rb

avec une migration pour ajouter le champ
https://github.com/parisrb/rubyparis.org/tree/master/db/migrate

et un changement du visuel
https://github.com/parisrb/rubyparis.org/blob/master/app/views/lineup/_sponsors.slim
