### ISSUE TITLE
Proposition Design 2019

### ISSUE THREAD

**Issue by simonc** [parisrb/paris-rb.org#46]
Hello la team,

I'm back! 👋  Et comme on m'a toujours dit de ne pas arriver les mains vides, j'aimerais soumettre à votre avis l'idée d'un redesign du site. Je n'ai pas encore toutes les pages, j'attends déjà vos retours.

Je vous souhaite un super réveillon et vous dis à l'année prochaine !

Bisou bisou ❤️ 

-----

![rubyparis-desktop](https://user-images.githubusercontent.com/119303/50563989-d0d1c100-0d21-11e9-8aa6-916236b11d9d.png)
---
![rubyparis-mobile](https://user-images.githubusercontent.com/119303/50563991-d0d1c100-0d21-11e9-81f9-a091eb481990.png)
---
![rubyparis-mobile-form](https://user-images.githubusercontent.com/119303/50563990-d0d1c100-0d21-11e9-9b1b-f23f16ffbf3c.png)

**Comment by yannski** [comment]
C'est vraiment super top. Et surtout, c'est mieux que le design du site actuel ;-P

**Comment by yannski** [comment]
Je prévois une migration vers Rails 6 très prochainement parce que j'ai pas mal de nouilles en environnement de développement :)

**Comment by simonc** [comment]
On peut se sync sur le sujet si tu veux.

**Comment by adrienpoly** [comment]
@simonc hello je n’avais pas vu cette initiative. Un gros redesign a été fait dans #223. 

Hésite pas si tu souhaites apporter des évolutions sur la base du travail que tu avais initié
