### ISSUE TITLE
Proposer des talks : ajouter date, twitter (speaker) et une position pour le lineup (admins)

### ISSUE THREAD

**Issue by tibastral** [parisrb/paris-rb.org#7]

**Comment by abelards** [comment]
Je propose aussi de donner la main aux speakers pour la date :
- soit le jour (bof)
- soit le mois (cool)
- soit un choix "prochain meetup / meetup d'après"

**Comment by tibastral** [comment]
+1

**Comment by abelards** [comment]
L'ordre sûrement dans le modèle pour l'avoir par défaut
https://github.com/parisrb/rubyparis.org/blob/master/app/models/sponsor.rb

avec une migration pour ajouter le champ
https://github.com/parisrb/rubyparis.org/tree/master/db/migrate

et un changement du visuel en conséquence (je verrais bien les sponsors annuels 2x plus gros)
https://github.com/parisrb/rubyparis.org/blob/master/app/views/lineup/_sponsors.slim
